### PR TITLE
Examples added for flatten/unflatten, sekelton for specification.

### PR DESCRIPTION
**Pull request by mariokonrad**

### CODE REVIEW

**Comment by nlohmann** [comment]
Do we really want to put flatten/unflatten into the standard? I'm not sure whether it is a useful feature - I only implemented it into nlohmann/json, because it was part of the library I looked at for examples of JSON Pointers. I never got any feedback/questions/issues from users about it.

**Comment by mariokonrad** [comment]
To be honest, I don't know, you're the expert. There is a question on StackOverflow about this: [here](https://stackoverflow.com/questions/24833379/why-and-when-do-we-need-to-flatten-json-objects). To me it seemed to be a good idea and the addition to the proposal is not that large.

**Comment by nlohmann** [comment]
Thanks for the link. I shall have a look.

**Review by nlohmann — APPROVED** [review]
Looks good to me.

**Pull request merged**
