### PR TITLE
proposal title change

### PR DESCRIPTION
**Pull request by DBJDBJ**
maybe, perhaps, could be better :)

### CODE REVIEW

**Comment by mariokonrad** [comment]
What's the motivation behind changing the title?

Regarding other papers (see http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/), almost all of them tell a story without technical aspects ("Fixed-Point Real Numbers", "C++ Concurrent Queues", "A Unified Executors Proposal for C++").

**Comment by DBJDBJ** [comment]
"library" is made of 1 .. N types, functions, mechanisms, has configuration, has root namespace, is deployed separately ...etc. `std::` is a library. Example: `std::basic_string<>` is not a library

If I understand the `std::json` scope right it is a type in the std:: namespace ... it is not a library or
a subspace .. like `std::filesystem` for example. 

Thus the motivation 

Perhaps **_"std::json"_** , might be a better name ?

**Comment by mariokonrad** [comment]
Technically `std::` is a namespace, while `libstdc++` and `libc++` are libraries. Also, a single header file might be seen as a library (`json.hpp`?), it it bears the semantics of one. And it may or may not provide multiple types, etc. It's also perfectly valid to have multiple libraries live in the same namespace and vice versa.

Considering the wording of the standard (browseable here: http://eel.is/c++draft/, LaTeX sources here: https://github.com/cplusplus/draft), many things are called "library": "Iterators Library", "Atomic operations Library", "Time Library", and so on and on. Based on this, I make the case that "JSON Library" is probably the best name.

In the end, the proposal is called P0760 and will not be up- or downvoted based on an arbitrary title, but its content.

**Comment by DBJDBJ** [comment]
-  my title proposal is not "arbitrary"
- there is WG21 taxonomy (not documented AFAIK), but obviously present
- std lib is standard C++ library. 
- std::filesystem is an example of sub name space (btw: even that was not named a "library")
- everything else are types, etc ...
- std::json is proposed to be part of an library ... logically it can not be a "library", maybe a sub-library , but that is not the  terminology/taxonomy in use ... there are "sub name spaces" but there are no "sub libraries" or "libraries"

I really see no reason for debate. Accept WG21 terminology/wording/taxonomy or not. My advice is "not to ruffle the feathers in the wrong way..."

**Comment by mariokonrad** [comment]
> I really see no reason for debate

On this I agree. In the end, this appears to me like bikeshedding. I'd rather focus on content.

Changing the title
- is devoid of substance/content
- does not add any improvement, does not describe the proposal any better/clearer

Will not merge.

**Pull request closed without merging**
