### PR TITLE
Can work on this, for a serious refresh.

### PR DESCRIPTION
**Pull request by DBJDBJ**

### CODE REVIEW

**Comment by nlohmann** [comment]
Thanks!

**Comment by DBJDBJ** [comment]
Tiny precondition:  I need to be member of the crew. work on the separate branch, releases discussed and made, roadmap and all that bureaucracy, modern readers demand ...

My incentive is this: "utf8/char8_t is essential ... json is essential ... we can not wait for the year 2023..."

**Comment by nlohmann** [comment]
@mariokonrad What do you think?

**Comment by mariokonrad** [comment]
I'm sorry for not doing anything for so long, and I would like to think to not have given up on the idea of a proposal, which I still think would be worth doing. Unfortunately, during the last two years I was very occupied with work, and maybe this proposal was not in the top spot of my priorities.

Personally, I'd appreciate help from someone who steps up and is willing to actively participate, sharing the effort. Which means I still would like to participate (I hope this does not sound too silly, for someone as inactive as I was).

So... I could imagine, a PR/review/discussion based approach could work. Ultimately, why not at least give it a try.

I'd propose to adhere to the advice (see https://github.com/nlohmann/std_json/issues/7#issuecomment-315841434) from Louis Dionne (@ldionne) to have a proposal focusing on the motivation and usage, without all the technical/specification wording. A proposal to publish to the commitee, to be talked about, to have a discussion. The technical wording will/could follow later. That was maybe the wrong approach I took that (long) time ago.

**Comment by DBJDBJ** [comment]
sounds reasonable ... one clarification: "serious refresh" from the title, actually means: "std::json proposal, serious refresh".

**Comment by mariokonrad** [comment]
@nlohmann Your opinion?

**Comment by nlohmann** [comment]
@mariokonrad I would be happy for anyone pushing this forward. I do not plan to spend much time on this - it just does not fit the kind of stuff I would like to do beside work and family...

**Comment by mariokonrad** [comment]
@nlohmann I understand. Would you mind to keep the repository around for now?

**Comment by nlohmann** [comment]
I'll keep it around of course and add @DBJDBJ as collaborator.

**Comment by DBJDBJ** [comment]
Vielen danke Niels.

**Pull request merged**
